# Generated by Django 5.2.4 on 2025-07-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_room_description_alter_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEditRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_room', models.BooleanField(default=False)),
                ('edit_room', models.BooleanField(default=False)),
                ('delete_information_room', models.BooleanField(default=False)),
                ('delete_room', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='add_edit_room',
        ),
    ]
