# Generated by Django 5.2.4 on 2025-07-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='tenant',
        ),
    ]
