# Generated by Django 5.2.4 on 2025-07-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_reservation_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
    ]
