# Generated by Django 5.2.4 on 2025-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
